### ISSUE TITLE
Duux ThreeSixty template switch displays log error every morning

### ISSUE THREAD

**Issue by gvssr** [gvssr/home-assistant-config#5]
**Description**
Every morning at 08:00 when the heater automations run, the power switch for the Duux ThreeSixty displays an error in the log.

**Expected behavior**
Should turn on without error.

**Environment**
 - Home Assistant Core: core-2021.10.6

**Details & logs**
```
  - platform: template
    switches:
      threesixty:
        friendly_name: Duux ThreeSixty Power
        icon_template: mdi:hvac
        turn_on:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: 'auto'
            entity_id: climate.tuya_threesixty_v2
          - service: scene.turn_on
            target:
              entity_id: scene.threesixty_boost_mode
        turn_off:
          service: climate.set_hvac_mode
          data:
            hvac_mode: 'off'
          entity_id: climate.tuya_threesixty_v2
```

```
Logger: homeassistant.helpers.script.duux_threesixty_power
Source: helpers/script.py:1344
First occurred: 08:00:00 (1 occurrences)
Last logged: 08:00:00

Duux ThreeSixty Power: Already running
```
